### ISSUE TITLE
warning when linking into an iOS widget build

### ISSUE THREAD

**Issue by thosmos** [onekiloparsec/SwiftAA#108]
I'm getting warning about linking to the SwiftAA library in a widget app.  It says it's not safe.  Is there some way around this?  Why is it considered unsafe for an iOS extension?

ld: warning: linking against a dylib which is not safe for use in application extensions: /Xcode/DerivedData/Build/Products/Debug-iphoneos/PackageFrameworks/SwiftAA.framework/SwiftAA

**Comment by onekiloparsec** [comment]
Hi. Good question, I have no idea. This is the first time this problem is reported to me.

**Comment by thosmos** [comment]
This is the only thing I've found that offers a suggestion of something that might help

https://stackoverflow.com/questions/52885293/warning-message-linking-against-a-dylib-which-is-not-safe-for-use-in-application

I'll look into building the code myself so that I might be able to tweak the build settings a bit.

**Comment by thosmos** [comment]
I wound up just passing the needed data to the widget using user settings.
