### ISSUE TITLE
Adding via Swift Package Manager

### ISSUE THREAD

**Issue by wilks7** [onekiloparsec/SwiftAA#112]
I'm having issues adding the repo via Swift Package Manager. 

When I user master branch try to just check off only SwiftAA I get an error on compiling for AAPlus under: 
`Semantic Issue: must be initialized by a constant expression`

When I try just SwiftAA using specific version 2.3.2 or 2.2.2 I get the error: 
`Build input file cannot be found`

When I try to add via SPM and check off AAPlus and SwiftAA I get the error: 
`Swift package target 'AAPlus' is linked as a static library by 'myAppName' and 'AAPlus' but cannot be built dynamically because there is a package product of the same name`

![Screen Shot 2022-08-15 at 1 52 21 PM](https://user-images.githubusercontent.com/8426471/184690300-620fd5da-63ab-4a89-a46c-7b9066f3a41f.png)

![Screen Shot 2022-08-15 at 2 12 03 PM](https://user-images.githubusercontent.com/8426471/184691668-a6495632-c239-4638-802c-9776589ba69b.png)

![Screen Shot 2022-08-15 at 1 55 29 PM](https://user-images.githubusercontent.com/8426471/184690302-774c5814-9a7d-4673-b3c4-81e9629c1fb8.png)

**Comment by onekiloparsec** [comment]
Thanks for the bug report. The master branch is currently stuck in the last phase of a migration to a much newer AA+ code. I have some trouble making the tag and the release. Unfortunately, I am not using the SPM myself in other projects and don't have much XP on it.

**Comment by onekiloparsec** [comment]
@wilks7 could have a look now we have merged @vincentneo PR? AFAICT there is no need for a release for you to, at least, try.
