### ISSUE TITLE
JulianDate implementation is flawed

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#14]
This code

    let date = Date(timeIntervalSinceReferenceDate: 503975049.303508)
    print(date)
    print(date.julianDay().date())

Results in

    2016-12-21 01:04:09 +0000
    2016-12-21 01:09:12 +0000 // ???

**Comment by onekiloparsec** [comment]
Hm... good candidate for a fix-n'-unit-test session.
