### ISSUE TITLE
NumericType suggestion

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#16]
I think NumericType.value should be immutable. We don't actually use this mutability anywhere, but it makes implementations a bit more complicated. What you think?

**Comment by onekiloparsec** [comment]
Of course, this makes a lot of sense. NumericType is intended to behave like any other builtin numeric types (`Float`, `Double`), but with basic transforms in the tricky business of physical units. Please, feel free to go ahead. I'm having an intense end of the year at work, and I couldn't do much during the week anyway.
