### ISSUE TITLE
Fix Venus Equatorial coordinates test

### ISSUE THREAD

**Issue by onekiloparsec** [onekiloparsec/SwiftAA#24]
Strange, this was working before, @alex-vasenin no?

**Comment by alex-vasenin** [comment]
It's a new test I added today. It's actually a prerequisite to make a rise/transit/set times test (see AA p.103).

**Comment by alex-vasenin** [comment]
I think I found what's wrong: AA p.103 refers to **geocentric** equatorial coordinates of Venus, while `Venus.equatorialCoordinates` is **heliocentric** equatorial coordinates. So, basically, test implementation is wrong. But the real question is: what's the best way to deal with this confusion? Should we split coordinates to heliocentric and geocentric to use Swift types as a safety net? Should we add heliocentric and geocentric coordinate varieties to all celestial objects? Should we introduce `Observer`? What you think?

**Comment by onekiloparsec** [comment]
Very interesting questions. The way I see it, is that SwiftAA is intended to a professional audience first (but I may be wrong). Most of research does not concern solar system, hence default to **heliocentric**. This is all of my worked started (as a former pro).

However, SwiftAA, and it is also intended to be used to a (much) larger audience of general public (and teachers etc), which is probably more interested to solar system problems (like rise, transit and set).

Conclusion? We should expose both, of course, in an explicit way, of course. To me, equatorial coordinates remain **heliocentric** first, since the equatorial system is solar-based. Geocentric equatorial coordinates are a special case, also called "aparent", mostly relevant for planets as seen from earth. The day we need to make those computations from Mars or the Moon, the equatorial system will remain, while the meaning of "apparent" will have to specify the place.

What do you think?

**Comment by alex-vasenin** [comment]
Well, as an amateur astronomer, I always thought of equatorial coordinates exclusively from observational (i.e. **geocentric**) point of view. It was quite a surprise for me to find it's not always the case. We should stick to the scientific names for sure, but preferably to avoid confusion. I guess the only option is `HeliocentricEquatorialCoordinates` and `GeocentricEquatorialCoordinates`.

**Comment by onekiloparsec** [comment]
I've added a method `.toApparentEquatorialCoordinates`, but the Venus test still fails. 

There is something we still don't understand. I must say I am not 100% confortable with the differences between equinox, epoch, true and mean obliquity of ecliptic... But we are getting closer.

My small concern with the two different types `HeliocentricEquatorialCoordinates` and `GeocentricEquatorialCoordinates` is that they seem to designate two different specialisations of a same underlying thing. While in fact only the heliocentric... Okay, okay, maybe this is a professional bias! 

Anyway, having these two types would imply to have transformations between them. With my new implementation, this isn't needed, as it both are derived from ecliptic ones (at least for Planets).

But, if you have a better idea, I'm open!
