### ISSUE TITLE
RiseTransitSetTimes is broken

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#31]
`RiseTransitSetTimes` is broken because it uses `CelestialBody.equatorialCoordinates` which are **heliocentric** coordinates instead of **geocentric** coordinates (related to issue #24)

**Comment by onekiloparsec** [comment]
Interestingly, similar to the discussion we have in #25 I see `.equatorialCoordinates` as a true property of a CelestialBody. While the apparent geocentric ones needs an observer location to be computed.

Hence, one should add an `.apparentEquatorialCoordinates(observerCoordinates:)` function to CelestialBodies.

**Comment by onekiloparsec** [comment]
All wrong. The difference between heliocentric coordinates and geocentric ones, is computed by taking the **mean** obliquity of the ecliptic for the former, and the **true** one for the latter, thus taking into account aberration and nutation.
