### ISSUE TITLE
Can't get ecliptic to equatorial transformation working

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#5]
Here is the test code:

    let now = Date().julianDay()
    let sun = Sun.init(julianDay: now)
    print(now) // OK
    print(sun.eclipticCoordinates) // OK
    print(sun.equatorialCoordinates) // RA is OK, but DEC should be -23°, not +55°

And here is the output:

    JulianDay(value: 2457742.6550525003)
    EclipticCoordinates(celestialLongitude: SwiftAA.Degree(value: 268.6910301599379), celestialLatitude: SwiftAA.Degree(value: -1.8868903201079716e-05), epoch: SwiftAA.JulianDay(value: 2451545.0))
    EquatorialCoordinates(rightAscension: SwiftAA.Hour(value: 17.847912733146728), declination: SwiftAA.Degree(value: 54.978633717748345), epoch: SwiftAA.JulianDay(value: 2451545.0))

What I'm doing wrong?

**Comment by onekiloparsec** [comment]
Hm... I'll definitely check. Something is wrong here.

**Comment by alex-vasenin** [comment]
It looks like the problem is the last parameter in the calls to `KPCAACoordinateTransformation_Ecliptic2Equatorial` should be obliquity of ecliptic (not epoch)

**Comment by onekiloparsec** [comment]
Hm, I've worked on this recently, I remember to have note to myself that I was making a confusion between epoch and obliquity because they are both named `epsilon`. Damn. Must be careful with this.

**Comment by onekiloparsec** [comment]
Follow-up in #17
