### ISSUE TITLE
Cannot compile SwiftAA with Swift4

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#58]
Even with SWIFT_VERSION=3.2, due to the changes in Swift Standard Library, Xcode 9 says `.../SwiftAA/Angles.swift:96:15: Type 'ArcMinute' does not conform to protocol 'Numeric'` for all `NumericType`s

**Comment by onekiloparsec** [comment]
Hm... I haven't opened Xcode9 yet (but I have it installed!). Too busy [elsewhere](https://www.arcsecond.io). I'll have a look!

**Comment by onekiloparsec** [comment]
Hm, Xcode requires to implement these stubs (here for `Degree` but similar for others):

    public static func *(lhs: Degree, rhs: Degree) -> Degree {
        <#code#>
    }
    
    public static func *=(lhs: inout Degree, rhs: Degree) {
        <#code#>
    }

No idea how to deal with it right now.

**Comment by rodericj** [comment]
I just ran into this as well. I'd be down to help out. I started along the path described above but ran into some issues with `public typealias Magnitude = <#type#>` in the Xcode suggestion when I hit the `Fixit` button. I'll have to look at it a bit later.

**Comment by onekiloparsec** [comment]
Hm, I wish we could finish milestone 2.0 before migrating to Swift4...

**Comment by onekiloparsec** [comment]
I renamed the issue, because it is formally possible to compile current SwiftAA with Xcode9. But we have to work on Swift4 (milestone 3.0)

**Comment by onekiloparsec** [comment]
This is now done since quite a while. Closing.

**Comment by rodericj** [comment]
Thank you!
