### ISSUE TITLE
Accessing `Moon.eclipticCoordinates` getter results in infinite recursion

### ISSUE THREAD

**Issue by alex-vasenin** [onekiloparsec/SwiftAA#6]
See screenshot
![2016-12-20_0348](https://cloud.githubusercontent.com/assets/8776784/21334299/4fa03d12-c667-11e6-8f0e-361b289f6a78.png)

**Comment by onekiloparsec** [comment]
Oups... You're right. There must be KPCAA methods somewhere to get ecliptic corodinates.
