### ISSUE TITLE
Calculate Moonphase for Date

### ISSUE THREAD

**Issue by Styx665** [onekiloparsec/SwiftAA#63]
Hi,
I just stumbled over this great repo. 
I'm looking for a function to calculate the moon phase for a specific Date. I'm pretty sure this task can be solved with your code, but I'm a absolute beginner at this topic.
Could you please tell me which functions I need ?

**Comment by onekiloparsec** [comment]
One you need is to instantiate a Moon object for a given date/julian day, and the following 3 methods you are interested in are: `phaseAngle()`, `illuminatedFraction()` and `positionAngleOfTheBrightLimb()`.

**Comment by onekiloparsec** [comment]
Noe however that unit tests are missing for this part. I'll make sure to cover code with it for milestone 2.0.
