### ISSUE TITLE
clarification - Astronomical space coordinate and time conversion

### ISSUE THREAD

**Issue by johndpope** [onekiloparsec/SwiftAA#74]
I found this repo -  https://github.com/DJBen/SpaceTime

It does azimuth and altitude / right ascension and declination - can swiftAA do this out of the box?
![image](https://user-images.githubusercontent.com/289994/32991721-fe248254-cd0e-11e7-9250-2b9fa74ac240.png)

if so - do you have a snippet of code to share?

https://github.com/ThumbWorks/AugmentedSolarSystem/issues/51

**Comment by onekiloparsec** [comment]
Hi John. Sorry for not following all the details, I am pretty busy these days. But to answer your question, yes, SwiftAA do this out of the box. These are the transformation of EquatorialCoordinates into Horizontal ones. Check the `makeHorizontalCoordinates` method of the `EquatorialCoordinates` class.

**Comment by johndpope** [comment]
thanks Cedric, I'll share a gist when I get to it.
