### ISSUE TITLE
Planet aspects /conjunction -  clarification on methods for PlanetaryPhenomena 

### ISSUE THREAD

**Issue by johndpope** [onekiloparsec/SwiftAA#75]
http://onekiloparsec.github.io/SwiftAA/Protocols/PlanetaryPhenomena.html

inferiorConjunction(mean:) Default implementation
superiorConjunction(mean:) Default implementation
opposition(mean:) Default implementation
conjunction(mean:) Default implementation
easternElongation(mean:) Default implementation
westernElongation(mean:) Default implementation
station1(mean:) Default implementation
station2(mean:) Default implementation
elongationValue(eastern:) Default implementation

this website 
http://www.theastrologer.com/wap/todaysaspect.php?aspect=yesterday

can determine aspects for today's date.

eg. Dec 2nd 2017
Mercury Conjunct Saturn (    ) 
Mars Opposite Uranus (    ) 
Jupiter Trine Neptune (    ) 

![screen shot 2017-12-02 at 7 20 58 pm](https://user-images.githubusercontent.com/289994/33521092-ff00b2e2-d795-11e7-9624-073fbf41159a.png)

Forgive the newbie question - but can that be inferred from methods above?
Did you ever implement these methods in your code? 
Do you have a gist you could share?

**Comment by onekiloparsec** [comment]
Sorry for the answer, but I will have a hard time trusting meaning of words in a Astrology website. "Opposite" ? "Conjunc"? Could all have twisted meaning. I have no time to loose here. Usually, this goes into insane and never-ending discussions with people who can't hear explanations. You may find this hard judgement, and you'd be right. Experience matters, sorry. Try to ask questions that are slightly better articulated.
