### ISSUE TITLE
Compiling for Catalyst app

### ISSUE THREAD

**Issue by BrandonSlaght** [onekiloparsec/SwiftAA#85]
Hello,

Long time lurker for this project.  I'm currently using this framework in one of my apps and was wondering if there was a way to build a Catalyst version of this framework (currently using Carthage).  Seems like Carthage should be able to generate one since it already builds both iOS and Mac versions.  
Appreciate the help and sorry if I'm asking in the wrong place.

**Comment by onekiloparsec** [comment]
Hello Brandon. You are in the right place, no worries. I haven't switched to Catalina yet, and I think this is needed for playing with Catalyst, right ? I am a bit lagging behind Apple developer annoucements... But of course, my goal is to make SwiftAA useful on every possible ways. I will probably upgrade this weekend and have a look at this.

**Comment by BrandonSlaght** [comment]
Hey thanks man!  Appreciate all the work you do on this project.  Let me know if you want a tester or anything.  Cheers!

**Comment by onekiloparsec** [comment]
Hi Brandon. As far as I can tell (but I really didn't read much yet on Catalyst), there is no "Catalyst" version to be made, since the framework is supposed to be compilable in every platform (hence iOS and iPadOS... oh wait, I haven't tried iPadOS specifically). Ok will do.

**Comment by onekiloparsec** [comment]
I have pushed updates to the project, updated AA+ version from 1.99 to 2.08, upgraded to Swift5 and enabled Catalyst. If Travis succeeds with all tests, I'll make a tag and a release tomorrow but it looks good. You can have a try.

**Comment by onekiloparsec** [comment]
Travis is passing, Tag is made, release v2.1.0 is out.
