### ISSUE TITLE
Ascendant

### ISSUE THREAD

**Issue by cmaldonado80** [onekiloparsec/SwiftAA#87]
Is their a way to calculate the Ascendant 
("The ascendant ( , Asc or As), is the zodiacal sign and degree that is ascending on the eastern horizon at the specific time and location of an event").   
Getting the degree that is in the eastern horizon at any given time.

**Comment by onekiloparsec** [comment]
I am not sure to understand 100%. Let say we are located at some place on Earth at a given date.

It is easy to determine the direction of the East. But what is "degree" in that context ? A guess the "sign" is some region corresponding to a given constellation, right ?

**Comment by cmaldonado80** [comment]
Ascendant is the .ApparentGeocentricLongitude of the East at any given time. 
The point of  "sunrise" - "expectedRise" of the East

Example Venus expectedRise for today was at a certain hour with  a .planetaryDetails.ApparentGeocentricLongitude of 268. Venus was rising in the east = Ascendant. At that point, the Ascendant was also 268
30 minutes later, Venus .planetaryDetails.ApparentGeocentricLongitude is still 268( 28 Sagittarius)
but the East(Ascendant)  ApparentGeocentricLongitude is now at 275 ( 5 Capricorn)


![IMG_0413](https://user-images.githubusercontent.com/17576575/69500965-cc783e80-0ec5-11ea-913f-cf06c255cdca.jpg)
![IMG_0414](https://user-images.githubusercontent.com/17576575/69500970-d4d07980-0ec5-11ea-9a58-702e7bef333d.jpg)
![IMG_0416](https://user-images.githubusercontent.com/17576575/69500974-dc901e00-0ec5-11ea-86fc-c7874b35d607.jpg)

**Comment by onekiloparsec** [comment]
Cleaning up obsolete issues in 2023.
