### ISSUE TITLE
Compile Error with XCode 11, Swift 4.x

### ISSUE THREAD

**Issue by gregav** [onekiloparsec/SwiftAA#89]
Hi,

I am getting several compile errors:
Type 'Day' does not conform to protocol 'AdditiveArithmetic'...
Type 'Degree' does not conform to protocol 'AdditiveArithmetic'....

Thank you

**Comment by onekiloparsec** [comment]
Hi. Are you on the `swift4` branch ? 

I checked out this branch, and run the tests suites with success. I'm using Xcode 11.3.1.

**Comment by gregav** [comment]
Hi,
I am using pods, should I add extra in version or something. I have tried also ob empty project. The same.

**Comment by onekiloparsec** [comment]
Could you post here your Podfile for me to test?

**Comment by gregav** [comment]
Here I have packed whole test project

https://www.dropbox.com/s/pn150ed5rlcv4mf/astro.zip?dl=0 <https://www.dropbox.com/s/pn150ed5rlcv4mf/astro.zip?dl=0>

I am using latest XCode Version 11.4 (11E146)


thank you for help,
best regards,
Grega

**Comment by onekiloparsec** [comment]
Just opened your project and compiled. It fails because of an error which is the issue #90 Will make an updated release today.

**Comment by onekiloparsec** [comment]
Fixed. Upgrade to v2.2.3. You may consider support at some point, thanks! https://patreon.com/onekiloparsec
