### ISSUE TITLE
Compile Errors with Xcode 11.4 Update NumericType does not conform to protocol 'AdditiveArithmetic'

### ISSUE THREAD

**Issue by makramia** [onekiloparsec/SwiftAA#90]
I updated my Xcode to 11.4 and got all below errors:

Type 'Magnitude' does not conform to protocol 'AdditiveArithmetic'
Type 'Day' does not conform to protocol 'AdditiveArithmetic'
Type 'Hour' does not conform to protocol 'AdditiveArithmetic'
Type 'Minute' does not conform to protocol 'AdditiveArithmetic'
Type 'Second' does not conform to protocol 'AdditiveArithmetic'
Type 'AstronomicalUnit' does not conform to protocol 'AdditiveArithmetic'
Type 'Parsec' does not conform to protocol 'AdditiveArithmetic'
Type 'Meter' does not conform to protocol 'AdditiveArithmetic'
Type 'Kilometer' does not conform to protocol 'AdditiveArithmetic'
Type 'JulianDay' does not conform to protocol 'AdditiveArithmetic'
Type 'Degree' does not conform to protocol 'AdditiveArithmetic'
Type 'ArcMinute' does not conform to protocol 'AdditiveArithmetic'
Type 'ArcSecond' does not conform to protocol 'AdditiveArithmetic'
Type 'Radian' does not conform to protocol 'AdditiveArithmetic'

**Comment by makramia** [comment]
I solved the issue by extending NumericType protocol to AdditiveArithmetic in NumericType.swift file

**public protocol _NumericType: AdditiveArithmetic** {
    var value: Double { get }
    init(_ value: Double)
    func rounded(toIncrement increment: Self, rule: FloatingPointRoundingRule) -> Self
}

**Comment by onekiloparsec** [comment]
Ok, thanks. I'll have a look to make an update release.

**Comment by onekiloparsec** [comment]
Currently fixing the issue but some new codesign errors appeared ???

**Comment by onekiloparsec** [comment]
Fixed. Upgrade to v2.2.3. You may consider support at some point, thanks! https://patreon.com/onekiloparsec
